spring:
    # JPA
    jpa:
      hibernate:
        ddl-auto: validate
      show_sql: true
      properties:
          hibernate:
            format_sql: true

    # JWT
    jwt:
      secret: 12345678901234567890123456789012

    # liquibase
    liquibase:
      change-log: classpath:config/liquibase/master.xml
#        enabled: false
    social:
      kakao:
        url:
          profile: https://kapi.kakao.com/v2/user/me
      google:
        url:
          profile: https://www.googleapis.com/oauth2/v3/userinfo


# logging
logging:
    level:
        org:
          hibernate:
                type:
                  descriptor:
                          sql: trace

# server
server:
  error:
    whitelabel:
          enabled: false


